openapi: "3.0.0"
info:
  title: Express Boilerplate API
  version: "1.0.0"
  description: Template API with Swagger ready

servers:
  - url: http://localhost:5000

paths: {} 
components:
  schemas: {}